language: python
python:
 - 3.6
before_install:
 - python --version
 - pip install -U pip
install:
 - pip install -r requirements.txt
addons:
 sonarcloud:
  organization: "geekcode"
script:
 - pytest
 - behave ./test_aceptance/
 - sonar-scanner

